local LSM = LibStub("LibSharedMedia-3.0")

-- Generated by build_addon.py -- do not hand-edit.
-- Organic: |cFF98FF98 mint green   Classic: |cFFFF69B4 hot pink   Memes: |cFF32CD32 lime green

-- -------
-- ORGANIC (16 sounds)
-- -------
LSM:Register("sound", "|cFF98FF98Tones: Organic: Come In|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Come-In.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Done Deal|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Done-Deal.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Faster|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Faster.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Fragile|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Fragile.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Hammered|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Hammered.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Inharmonics|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Inharmonics.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Likeable|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Likeable.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Metallic|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Metallic.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Minimalist Gamelan|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Minimalist-Gamelan.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Minimalist Woodblock|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Minimalist-Woodblock.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Notified|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Notified.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Simple Task|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Simple-Task.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Spotless|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Spotless.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Struck With Grace|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Struck-With-Grace.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: The Cyclist|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-The-Cyclist.ogg]])
LSM:Register("sound", "|cFF98FF98Tones: Organic: Woodblock|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Woodblock.ogg]])

-- -------
-- CLASSIC (26 sounds)
-- -------
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Affirmed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Affirmed.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Alert|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Alert.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Answer|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Answer.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Arodue|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Arodue.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Attention|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Attention.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Bell|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Bell.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Bouncing|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Bouncing.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Check|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Check.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Chip|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Chip.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Chord|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Chord.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Classy|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Classy.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Clear|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Clear.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Confirmed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Confirmed.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Delayed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Delayed.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Dissonant|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Dissonant.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Done|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Done.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Enter|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Enter.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Finale|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Finale.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Friendly Reminder|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Friendly-Reminder.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Gentle Reminder|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Gentle-Reminder.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Remember The Milk|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Remember-The-Milk.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Sharp|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Sharp.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Swift|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Swift.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: Swop|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Swop.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: The Button|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-The-Button.ogg]])
LSM:Register("sound", "|cFFFF69B4Tones: Classic: The Switch|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-The-Switch.ogg]])

-- -----
-- MEMES (5 sounds)
-- -----
LSM:Register("sound", "|cFF32CD32Memes: Alert|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Alert.ogg]])
LSM:Register("sound", "|cFF32CD32Memes: Huh|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Huh.ogg]])
LSM:Register("sound", "|cFF32CD32Memes: Mistakes|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Mistakes.ogg]])
LSM:Register("sound", "|cFF32CD32Memes: Potion|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Potion.ogg]])
LSM:Register("sound", "|cFF32CD32Memes: WC2 Bloodlust|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-WC2-Bloodlust.ogg]])
