local LSM = LibStub("LibSharedMedia-3.0")

-- Generated by build_addon.py -- do not hand-edit.
-- Names start with a bare |r so LSM's raw-string sort puts every tone together at the end of the list.
-- Organic: |cFF98FF98 mint green   Classic: |cFFFF69B4 hot pink   Memes: |cFF32CD32 lime green

-- -------
-- ORGANIC (16 sounds)
-- -------
LSM:Register("sound", "|r|cFF98FF98T: Come In|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Come-In.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Done Deal|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Done-Deal.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Faster|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Faster.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Fragile|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Fragile.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Hammered|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Hammered.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Inharmonics|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Inharmonics.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Likeable|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Likeable.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Metallic|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Metallic.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Minimalist Gamelan|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Minimalist-Gamelan.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Minimalist Woodblock|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Minimalist-Woodblock.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Notified|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Notified.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Simple Task|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Simple-Task.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Spotless|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Spotless.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Struck With Grace|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Struck-With-Grace.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: The Cyclist|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-The-Cyclist.ogg]])
LSM:Register("sound", "|r|cFF98FF98T: Woodblock|r", [[Interface\AddOns\SharedMedia_Tones\sound\organic-Woodblock.ogg]])

-- -------
-- CLASSIC (26 sounds)
-- -------
LSM:Register("sound", "|r|cFFFF69B4T: Affirmed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Affirmed.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Alert|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Alert.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Answer|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Answer.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Arodue|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Arodue.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Attention|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Attention.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Bell|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Bell.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Bouncing|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Bouncing.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Check|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Check.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Chip|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Chip.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Chord|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Chord.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Classy|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Classy.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Clear|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Clear.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Confirmed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Confirmed.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Delayed|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Delayed.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Dissonant|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Dissonant.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Done|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Done.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Enter|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Enter.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Finale|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Finale.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Friendly Reminder|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Friendly-Reminder.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Gentle Reminder|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Gentle-Reminder.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Remember The Milk|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Remember-The-Milk.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Sharp|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Sharp.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Swift|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Swift.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: Swop|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-Swop.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: The Button|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-The-Button.ogg]])
LSM:Register("sound", "|r|cFFFF69B4T: The Switch|r", [[Interface\AddOns\SharedMedia_Tones\sound\classic-The-Switch.ogg]])

-- -----
-- MEMES (5 sounds)
-- -----
LSM:Register("sound", "|r|cFF32CD32T: Alert|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Alert.ogg]])
LSM:Register("sound", "|r|cFF32CD32T: Huh|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Huh.ogg]])
LSM:Register("sound", "|r|cFF32CD32T: Mistakes|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Mistakes.ogg]])
LSM:Register("sound", "|r|cFF32CD32T: Potion|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-Potion.ogg]])
LSM:Register("sound", "|r|cFF32CD32T: WC2 Bloodlust|r", [[Interface\AddOns\SharedMedia_Tones\sound\meme-WC2-Bloodlust.ogg]])
